/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plkj_studysample_Hello */

#ifndef _Included_com_plkj_studysample_Hello
#define _Included_com_plkj_studysample_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plkj_studysample_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_plkj_studysample_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
